name: Build OpenCV Android

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/26.3.11579264

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt update && sudo apt install -y ninja-build zip unzip wget ant

      - name: Set Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd /tmp
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-21" "platforms;android-34" "build-tools;34.0.0" "ndk;26.3.11579264"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Fix DNS
        run: |
          echo "140.82.114.4 github.com" | sudo tee -a /etc/hosts
          echo "185.199.108.133 github.com" | sudo tee -a /etc/hosts

      - name: Download OpenCV Source 4.10.0
        run: |
          wget https://github.com/opencv/opencv/archive/refs/tags/4.10.0.zip
          unzip 4.10.0.zip
          mv opencv-4.10.0 opencv

      - name: Configure CMake
        run: |
          cmake -S opencv -B build \
            -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 \
            -DANDROID_SDK_ROOT=$ANDROID_SDK_ROOT -DANDROID_NDK=$ANDROID_NDK_ROOT \
            -DBUILD_SHARED_LIBS=ON -DBUILD_FAT_JAVA_LIB=OFF -DBUILD_LIST=core,imgproc,imgcodecs \
            -DBUILD_JAVA=ON -DBUILD_opencv_java=ON -DBUILD_opencv_world=OFF \
            -DOPENCV_JAVA_SOURCE_ROOT=${{ github.workspace }}/opencv/modules/java \
            -DANDROID_ANT_EXECUTABLE=/usr/bin/ant \
            -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_EXAMPLES=OFF \
            -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_ANDROID_PROJECTS=OFF \
            -DANDROID_STL=c++_shared -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
            -DWITH_JPEG=OFF -DWITH_PNG=OFF -DWITH_TIFF=OFF -DWITH_WEBP=OFF \
            -DWITH_OPENEXR=OFF -DWITH_JASPER=OFF -DWITH_OPENJPEG=OFF -DWITH_IPP=OFF \
            -DWITH_TBB=OFF -DWITH_ADE=OFF -DWITH_EIGEN=OFF -DWITH_OPENCL=OFF \
            -DBUILD_ZLIB=ON -DBUILD_opencv_apps=OFF -DBUILD_ANDROID_SERVICE=OFF \
            -DBUILD_DOCS=OFF -DBUILD_PACKAGE=OFF \
            -DCMAKE_C_FLAGS="-Os -fvisibility=hidden -fdata-sections -ffunction-sections" \
            -DCMAKE_CXX_FLAGS="-Os -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections" \
            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--gc-sections"

      - name: Build OpenCV
        run: cmake --build build --parallel $(nproc)

      - name: Prepare and Strip Release Library
        run: |
          mkdir -p dist_opencv/arm64-v8a
          
          SO_FILE=$(find build -type f -name "libopencv_java4.so" | head -n 1)
          if [ -z "$SO_FILE" ]; then
            echo "Error: libopencv_java4.so not found!"
            exit 1
          fi
          
          echo "Found: $SO_FILE"
          cp "$SO_FILE" dist_opencv/arm64-v8a/
          
          STRIP_TOOL="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
          "$STRIP_TOOL" --strip-unneeded dist_opencv/arm64-v8a/libopencv_java4.so
          
          echo "--- Final Size ---"
          ls -lh dist_opencv/arm64-v8a/

      - name: Upload OpenCV Files
        uses: actions/upload-artifact@v4
        with:
          name: opencv-4.10.0-arm64-v8a-java
          path: |
            dist_opencv/arm64-v8a/libopencv_java4.so
            build/bin/opencv-4100.jar
          if-no-files-found: error